import type { Metadata } from "next";
import {Geist, Geist_Mono, Inter} from "next/font/google";
import "./globals.css";
import AppProvider from "@/components/app-provider";
import Link from "next/link";
import NavItems from "@/app/nav-items";

const geistInter = Inter({
    variable: "--font-inter",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};



export default function RootLayout({children,}: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html lang="en">
        <body
            className={`${geistInter.variable} `}
        >
        <AppProvider>
            <NavItems/>
            {children}
        </AppProvider>
        </body>
        </html>
    );
}
